version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    networks:
      - backend-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
